Main svc
SkorokhodovSemen/java-explore-with-me pull request #3
Opened 2024-03-31 13:09 UTC by SkorokhodovSemen

2024-04-01 09:45 UTC, SkorokhodovSemen commented
Привет! Готов улучшать код.
Не смог найти инфу, как в Query проверить размер переданного параметра List:
Абстрактный пример ниже
@Query(SELECT e FROM Entity e WHERE ((определить размер и сравнить с 0) OR e.user.id IN ?1))
Page<Entity> getEntityByUsersId(List<Long> usersId, Page page)

Как ни пытался сравнивать с {} и через array_length, не получается. Либо приводить параметр к массиву и передавать массив, а не список, либо заранее, при передаче в запросе пустого листа, определять его как null и работать с ним.

2024-04-02 06:18 UTC, VadimZharkov commented
> Привет! Готов улучшать код. Не смог найти инфу, как в Query проверить размер переданного параметра List: Абстрактный пример ниже @query(SELECT e FROM Entity e WHERE ((определить размер и сравнить с 0) OR e.user.id IN ?1)) Page getEntityByUsersId(List usersId, Page page)
> 
> Как ни пытался сравнивать с {} и через array_length, не получается. Либо приводить параметр к массиву и передавать массив, а не список, либо заранее, при передаче в запросе пустого листа, определять его как null и работать с ним.

А не надо длину определять в запросе. Оставить просто WHERE e.user.id IN ?1
Если список пустой, то в результирующем наборе данных будет тоже пусто.

2024-04-02 06:29 UTC, VadimZharkov commented on main-service/src/main/java/ru/practicum/categories/CategoryServiceImpl.java
> +    private void validFoundForCategory(Optional<Category> category, long catId) {
Optional как параметр метода обычно не используют. Т.к. рассмотрим например category:
category потенциально может иметь три значения null, Optional с null и Optional со значением.
И соответственно проверка д.б. if (category != null && category.isEmpty())
В общем перебор, и просто решили что как параметр Optional не использовать.

2024-04-02 06:39 UTC, VadimZharkov commented on main-service/src/main/java/ru/practicum/categories/CategoryServiceImpl.java
> +        Optional<Category> categoryOptional = categoryRepository.findById(catId);
Про  validFoundForCategory ниже написал. А здесь можно так написать
Category> category = categoryRepository.findById(catId)
    .orElseThrow(() -> new NotFoundException("Category not found"));
return CategoryMapper.toCategoriesDto(category));

2024-04-02 06:43 UTC, VadimZharkov requested changes
Можно улучшить

2024-04-02 07:49 UTC, SkorokhodovSemen commented
> > Привет! Готов улучшать код. Не смог найти инфу, как в Query проверить размер переданного параметра List: Абстрактный пример ниже @query(SELECT e FROM Entity e WHERE ((определить размер и сравнить с 0) OR e.user.id IN ?1)) Page getEntityByUsersId(List usersId, Page page)
> > Как ни пытался сравнивать с {} и через array_length, не получается. Либо приводить параметр к массиву и передавать массив, а не список, либо заранее, при передаче в запросе пустого листа, определять его как null и работать с ним.
> 
> А не надо длину определять в запросе. Оставить просто WHERE e.user.id IN ?1 Если список пустой, то в результирующем наборе данных будет тоже пусто.

Так в тот то и дело, что логика какая, если список пуст, то должно вернуть все. Там есть Endpoint, В который передается 3 Lista, и тест, в котором определяется, что если 3 листа пустые, то должен вернуть весь контент. Но не работает если оставить IN на пустой лист

2024-04-02 15:17 UTC, VadimZharkov commented
> > > Привет! Готов улучшать код. Не смог найти инфу, как в Query проверить размер переданного параметра List: Абстрактный пример ниже @query(SELECT e FROM Entity e WHERE ((определить размер и сравнить с 0) OR e.user.id IN ?1)) Page getEntityByUsersId(List usersId, Page page)
> > > Как ни пытался сравнивать с {} и через array_length, не получается. Либо приводить параметр к массиву и передавать массив, а не список, либо заранее, при передаче в запросе пустого листа, определять его как null и работать с ним.
> > 
> > 
> > А не надо длину определять в запросе. Оставить просто WHERE e.user.id IN ?1 Если список пустой, то в результирующем наборе данных будет тоже пусто.
> 
> Так в тот то и дело, что логика какая, если список пуст, то должно вернуть все. Там есть Endpoint, В который передается 3 Lista, и тест, в котором определяется, что если 3 листа пустые, то должен вернуть весь контент. Но не работает если оставить IN на пустой лист

Тогда через case и разные методы, как у тебя и сделано, насколько я увидел.

2024-04-02 15:17 UTC, VadimZharkov approved these changes

2024-04-02 15:40 UTC, merged