Feature location processing
SkorokhodovSemen/java-explore-with-me pull request #5
Opened 2024-04-03 16:00 UTC by SkorokhodovSemen

Добавил фичу с локациями. Что нового?

При создании ивента с координатами, происходил поиск в бд существующих локаций и обновлялось поле Location.
При создании ивента с неизвестными координатами, вносилась в бд неизвестная локация
Возможность админу изменять список неизвестных локаций, добавлять поля
Возможность админу удалять локации по id
Возможность обновлять локации по id
При выполнении запроса поиска событий, если локация была неизвестная, то локация обновилась автоматически, если администратор внес ее в бд
Возможность поиска событий по названию места, с внесением в статистику
Возможность поиска событий по id локации, с внесением в статистику

2024-04-03 16:08 UTC, SkorokhodovSemen commented
Локально сделанные тесты проходят, связано с тем, что они здесь запускаются после базовых, соответственно меняются id которые я указывал при создании собственных тестов.

2024-04-04 08:22 UTC, VadimZharkov reviewed
В  EventRequestServiceImpl во второй if никогда не зайдет
```
       if (!event.getState().equals(State.PUBLISHED)) {
            log.info("User with id = {} can't create eventRequest for event with id = {} " +
                    "because it's not PUBLISHED", userId, eventId);
            throw new ConflictException("You can't create eventRequest because it's not PUBLISHED");
        }
        if (event.getState().equals(State.CANCELED)) {
            log.info("User with id = {} can't create eventRequest for event with id = {} " +
                    "because it's CANCELED", userId, eventId);
            throw new ConflictException("You can't create eventRequest because it's CANCELED");
        }
 
```

2024-04-04 08:24 UTC, VadimZharkov commented on main-service/src/main/java/ru/practicum/events/EventServiceImpl.java
viewStatsDtos1 - названия переменных с цифиркой очень не приветствуются

2024-04-04 08:28 UTC, VadimZharkov reviewed
Нужно убрать из проекта весь закомментированный код

2024-04-04 08:29 UTC, VadimZharkov commented on main-service/src/main/java/ru/practicum/location/LocationRepository.java
> +    ;
это что)?

2024-04-04 08:35 UTC, VadimZharkov commented on main-service/src/main/java/ru/practicum/location/model/Location.java
> +@Data
Для сущностей применение @Data считается плохой практикой, т.е. по данной аннотации генерится hashCode и equals на основе всех полей. А сущность должна идентифицироваться по id.
https://stackoverflow.com/questions/75181366/why-jpa-buddy-complains-about-data-annotation-over-jpa-entity

2024-04-04 08:36 UTC, VadimZharkov commented on main-service/src/main/resources/schema.sql
> +'
закомментированный код нужно убрать

2024-04-04 08:38 UTC, VadimZharkov requested changes
Можно улучшить

2024-04-04 08:39 UTC, SkorokhodovSemen commented on main-service/src/main/java/ru/practicum/events/EventServiceImpl.java
Не заметил, видимо когда рефактор делал. Исправил

2024-04-04 08:40 UTC, SkorokhodovSemen commented on main-service/src/main/java/ru/practicum/location/LocationRepository.java
> +    ;
Упс))

2024-04-04 08:57 UTC, SkorokhodovSemen commented on main-service/src/main/java/ru/practicum/location/model/Location.java
> +@Data
Заменил на 
@Getter
@Setter
@ToString
@AllArgsConstructor 
И переопределил equals и hashcode

2024-04-04 09:16 UTC, VadimZharkov approved these changes

2024-04-04 09:18 UTC, merged